### ISSUE TITLE
I stock in login page when I use Udeler

### ISSUE THREAD

**Issue by noamangg** [sampathkumart/Electron-udeler#1]
I stock in login page when I use it when I press login it opens a new window then I login into my Udemy account but nothing happened
it opens like this
![Screenshot (171)](https://user-images.githubusercontent.com/71488276/148113944-5732038a-a23f-4eb5-b487-6505c66c0967.png)

**Comment by ozzyg28** [comment]
is there any fix for this? I tried different OS, app-arch, and nothing.
